=== matthiasferch/luz/packages/formats/schemas/pipeline.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Render pipeline",
  "$id": "pipeline.schema.json",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "cullMode": {
      "type": "string",
      "enum": ["none", "front", "back"]
    },
    "blendMode": {
      "type": "string",
      "enum": ["none", "additive", "transparent", "transmissive"]
    },
    "depthTest": {
      "type": "string",
      "enum": ["none", "never", "always", "equal", "notEqual", "less", "lessEqual", "greater", "greaterEqual"]
    },
    "depthMask": {
      "type": "boolean"
    },
    "colorMask": {
      "type": "array",
      "items": {
        "type": "boolean"
      },
      "minItems": 4,
      "maxItems": 4
    },
    "vertexShader": {
      "type": "string"
    },
    "fragmentShader": {
      "type": "string"
    }
  },
  "required": ["vertexShader", "fragmentShader"],
  "additionalProperties": false
}

=== matthiasferch/luz/packages/graphics/rendering/pipelines/volumetric-composite.pipeline.json
{
  "$schema": "../../../formats/schemas/pipeline.schema.json",
  "vertexShader": "./assets/shaders/composite.vertex.glsl",
  "fragmentShader": "./assets/shaders/volumetric-composite.fragment.glsl",
  "blendMode": "additive",
  "depthTest": "always",
  "depthMask": false,
  "colorMask": [true, true, true, false]
}
