=== matthiasferch/luz/packages/formats/schemas/skeletal-animation.schema.json
{
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "type": {
      "const": "skeletalAnimation"
    },
    "schemaVersion": {
      "const": 1
    },
    "keyframes": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "translation": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "time": {
                  "type": "number",
                  "minimum": 0
                },
                "value": {
                  "type": "array",
                  "items": {
                    "type": "number"
                  },
                  "minItems": 3,
                  "maxItems": 3
                }
              },
              "required": ["time", "value"],
              "additionalProperties": false
            },
            "minItems": 1
          },
          "rotation": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "time": {
                  "type": "number",
                  "minimum": 0
                },
                "value": {
                  "type": "array",
                  "items": {
                    "type": "number"
                  },
                  "minItems": 4,
                  "maxItems": 4
                }
              },
              "required": ["time", "value"],
              "additionalProperties": false
            },
            "minItems": 1
          },
          "scale": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "time": {
                  "type": "number",
                  "minimum": 0
                },
                "value": {
                  "type": "array",
                  "items": {
                    "type": "number"
                  },
                  "minItems": 3,
                  "maxItems": 3
                }
              },
              "required": ["time", "value"],
              "additionalProperties": false
            },
            "minItems": 1
          }
        },
        "required": ["translation", "rotation", "scale"],
        "additionalProperties": false
      },
      "minProperties": 1
    },
    "duration": {
      "type": "number",
      "exclusiveMinimum": 0
    },
    "playback": {
      "enum": ["loop", "once"]
    },
    "isAutoplayEnabled": {
      "type": "boolean"
    }
  },
  "required": ["type", "schemaVersion", "duration", "keyframes"],
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "skeletal-animation.schema.json",
  "title": "Skeletal animation",
  "additionalProperties": false
}

=== matthiasferch/luz/apps/editor/demo-assets/character/animations/b0204e0db479183cc2e008160b5434d5a5b909e5b515fac5b5c3cc8640d571e2.animation.json
{"duration":0.9,"isAutoplayEnabled":false,"keyframes":{"mixamorig:Head":{"rotation":[{"time":0,"value":[-0.06595735251903534,-0.0014931944897398353,-0.011938389390707016,0.997749924659729]},{"time":0.03333333333333333,"value":[-0.06893487274646759,-0.007755478844046593,-0.030779296532273293,0.9971160888671875]},{"time":0.1,"value":[-0.06279975920915604,-0.026949819177389145,-0.09216024726629257,0.9933964014053345]},{"time":0.13333333333333333,"value":[-0.05237302556633949,-0.03662316873669624,-0.12911932170391083,0.9895676374435425]},{"time":0.16666666666666666,"value":[-0.038869671523571014,-0.04441472515463829,-0.1638711541891098,0.9847145676612854]},{"time":0.2,"value":[-0.02597658522427082,-0.0504843033850193,-0.19225001335144043,0.9797022342681885]},{"time":0.23333333333333334,"value":[-0.016613155603408813,-0.05581832677125931,-0.2126321941614151,0.9753952622413635]},{"time":0.26666666666666666,"value":[-0.011205647140741348,-0.06110519543290138,-0.22568680346012115,0.9722170829772949]},{"time":0.36666666666666664,"value":[-0.006363976746797562,-0.07301236689090729,-0.2339775115251541,0.9694757461547852]},{"time":0.4,"value":[-0.005633881781250238,-0.07447472214698792,-0.2324051409959793,0.9697471857070923]},{"time":0.4666666666666667,"value":[-0.006449765060096979,-0.07688643783330917,-0.22897367179393768,0.9703699946403503]},{"time":0.5,"value":[-0.009158320724964142,-0.07942062616348267,-0.22443276643753052,0.9712046384811401]},{"time":0.5333333333333333,"value":[-0.013007822446525097,-0.0813518613576889,-0.21522678434848785,0.9730828404426575]},{"time":0.5666666666666667,"value":[-0.01737140491604805,-0.07983265072107315,-0.2005472034215927,0.976271390914917]},{"time":0.6,"value":[-0.0225343257188797,-0.07347051054239273,-0.18102873861789703,0.9804707765579224]},{"time":0.6333333333333333,"value":[-0.029022246599197388,-0.0634346529841423,-0.158135324716568,0.9849503040313721]},{"time":0.6666666666666666,"value":[-0.036517783999443054,-0.051786869764328,-0.1334671825170517,0.989025354385376]},{"time":0.7,"value":[-0.04412035271525383,-0.039927154779434204,-0.10822618007659912,0.9923438429832458]},{"time":0.7333333333333333,"value":[-0.05099138244986534,-0.02882540598511696,-0.08345872908830643,0.9947882294654846]},{"time":0.8666666666666667,"value":[-0.0644303560256958,-0.004775014705955982,-0.01921973191201687,0.9977257251739502]},{"time":0.9,"value":[-0.06541650742292404,-0.00262135430239141,-0.014226050116121769,0.9977532029151917]}],"scale":[{"time":0,"value":[1,0.9999999403953552,0.9999998807907104]},{"time":0.9,"value":[1,1,1]}],"translation":[{"time":0,"value":[8.419156074523926e-7,3.1424291133880615,-10.3218355178833]},{"time":0.03333333333333333,"value":[0.0000023264437913894653,3.142428398132324,-10.321823120117188]},{"time":0.1,"value":[0.0000033974647521972656,3.1424307823181152,-10.321856498718262]},{"time":0.13333333333333333,"value":[0.000002562999725341797,3.1424343585968018,-10.321824073791504]},{"time":0.2,"value":[0.0000022649765014648438,3.142437219619751,-10.321812629699707]},{"time":0.23333333333333334,"value":[0.000005304813385009766,3.142427444458008,-10.321843147277832]},{"time":0.26666666666666666,"value":[0.0000029802322387695312,3.1424365043640137,-10.32182788848877]},{"time":0.3,"value":[0,3.142430067062378,-10.32186222076416]},{"time":0.3333333333333333,"value":[0.0000045299530029296875,3.1424336433410645,-10.321834564208984]},{"time":0.4,"value":[0.0000026226043701171875,3.1424295902252197,-10.321856498718262]},{"time":0.4666666666666667,"value":[-0.000002384185791015625,3.142432689666748,-10.3218355178833]},{"time":0.5,"value":[0.00000476837158203125,3.142428398132324,-10.32186222076416]},{"time":0.5333333333333333,"value":[0.0000045299530029296875,3.14243221282959,-10.32181167602539]},{"time":0.6666666666666666,"value":[0.0000021457672119140625,3.142423391342163,-10.32184886932373]},{"time":0.7333333333333333,"value":[0.0000016689300537109375,3.1424286365509033,-10.321834564208984]},{"time":0.7666666666666667,"value":[0.0000025853514671325684,3.1424288749694824,-10.321858406066895]},{"time":0.8,"value":[0.000002629123628139496,3.1424264907836914,-10.321830749511719]},{"time":0.8666666666666667,"value":[0.000002682209014892578,3.142427921295166,-10.3218412399292]},{"time":0.9,"value":[0.0000017881393432617188,3.142430543899536,-10.321821212768555]}]},"mixamorig:HeadTop_End":{"rotation":[{"time":0,"value":[0,2.1827872842550278e-11,2.3646862246096134e-11,1]},{"time":0.9,"value":[-2.9103833926180656e-11,-8.240021442951218e-10,9.640643838793039e-11,1]}],"scale":[{"time":0,"value":[1,1,1]},{"time":0.9,"value":[1,1,1.0000001192092896]}],"translation":[{"time":0,"value":[0.0001550912857055664,6.6364006996154785,-18.474674224853516]},{"time":0.03333333333333333,"value":[0.00015401840209960938,6.6364006996154785,-18.474666595458984]},{"time":0.1,"value":[0.00015437602996826172,6.636399745941162,-18.474681854248047]},{"time":0.23333333333333334,"value":[0.00015425682067871094,6.636399269104004,-18.474666595458984]},{"time":0.26666666666666666,"value":[0.00015616416931152344,6.6364030838012695,-18.474687576293945]},{"time":0.3333333333333333,"value":[0.000152587890625,6.636396884918213,-18.47466278076172]},{"time":0.36666666666666664,"value":[0.00015473365783691406,6.63640022277832,-18.47467613220215]},{"time":0.43333333333333335,"value":[0.0001545548439025879,6.6363983154296875,-18.47466278076172]},{"time":0.6,"value":[0.00015550851821899414,6.6363983154296875,-18.474687576293945]},{"time":0.7,"value":[0.00015479326248168945,6.6364006996154785,-18.474653244018555]},{"time":0.8,"value":[0.00015425682067871094,6.63640022277832,-18.474653244018555]},{"time":0.8333333333333334,"value":[0.00015497207641601562,6.636399745941162,-18.47467803955078]},{"time":0.8666666666666667,"value":[0.0001551806926727295,6.636399269104004,-18.474660873413086]},{"time":0.9,"value":[0.00015431642532348633,6.63640022277832,-18.474674224853516]}]},"mixamorig:Hips":{"rotation":[{"time":0,"value":[-0.030604040250182152,-0.03687319532036781,0.05424172431230545,0.997377336025238]},{"time":0.03333333333333333,"value":[-0.025076959282159805,-0.03314392641186714,0.021739201620221138,0.9988994598388672]},{"time":0.1,"value":[-0.019106000661849976,-0.026017678901553154,-0.0465117022395134,0.9983960390090942]},{"time":0.13333333333333333,"value":[-0.01812940649688244,-0.02208569459617138,-0.07744953036308289,0.9965867400169373]},{"time":0.16666666666666666,"value":[-0.01800176128745079,-0.017799055203795433,-0.10463619232177734,0.9941883087158203]},{"time":0.2,"value":[-0.01865093596279621,-0.015683500096201897,-0.12794962525367737,0.9914812445640564]},{"time":0.23333333333333334,"value":[-0.019359348341822624,-0.014668789692223072,-0.1488163024187088,0.988566517829895]},{"time":0.26666666666666666,"value":[-0.019882552325725555,-0.012596596963703632,-0.17003385722637177,0.9851570725440979]},{"time":0.36666666666666664,"value":[-0.029406648129224777,-0.013479010201990604,-0.22850392758846283,0.9730054140090942]},{"time":0.4,"value":[-0.033522725105285645,-0.015435284934937954,-0.2439931482076645,0.9690744876861572]},{"time":0.4666666666666667,"value":[-0.03831891342997551,-0.00798722542822361,-0.28344184160232544,0.9581902623176575]},{"time":0.5,"value":[-0.04249703139066696,-0.006684967782348394,-0.3096259534358978,0.9498847723007202]},{"time":0.5333333333333333,"value":[-0.04668214172124863,-0.008102938532829285,-0.34128257632255554,0.938765823841095]},{"time":0.5666666666666667,"value":[-0.049661193042993546,-0.008655562065541744,-0.37608954310417175,0.9252110719680786]},{"time":0.6,"value":[-0.05203291028738022,-0.008391229435801506,-0.41110172867774963,0.9100645780563354]},{"time":0.6333333333333333,"value":[-0.052999429404735565,-0.009335117414593697,-0.4476455748081207,0.8925902247428894]},{"time":0.6666666666666666,"value":[-0.052200160920619965,-0.010106394998729229,-0.4871821105480194,0.8716803789138794]},{"time":0.7,"value":[-0.05300381779670715,-0.009860452264547348,-0.5398900508880615,0.8400072455406189]},{"time":0.7333333333333333,"value":[-0.05237613245844841,-0.008103764615952969,-0.579399585723877,0.81331866979599]},{"time":0.8666666666666667,"value":[-0.04765107482671738,-0.004960617981851101,-0.6615028977394104,0.748410701751709]},{"time":0.9,"value":[-0.04772299900650978,-0.004625274799764156,-0.6649097800254822,0.7453832626342773]}],"scale":[{"time":0,"value":[1,1,1]},{"time":0.9,"value":[1,0.9999999403953552,1]}],"translation":[{"time":0,"value":[0.4321664571762085,-0.06509952247142792,-98.39035034179688]},{"time":0.03333333333333333,"value":[0.4321664571762085,-0.06509952992200851,-98.32910919189453]},{"time":0.1,"value":[0.4321664571762085,-0.06509952247142792,-98.35215759277344]},{"time":0.13333333333333333,"value":[0.4321664571762085,-0.06509950757026672,-98.55325317382812]},{"time":0.16666666666666666,"value":[0.4321664571762085,-0.06509949266910553,-98.78742218017578]},{"time":0.2,"value":[0.4321664571762085,-0.06509948521852493,-98.87259674072266]},{"time":0.23333333333333334,"value":[0.4321664571762085,-0.06509948521852493,-98.86400604248047]},{"time":0.26666666666666666,"value":[0.4321664571762085,-0.06509948521852493,-98.89053344726562]},{"time":0.36666666666666664,"value":[0.4321664571762085,-0.06509950757026672,-98.62470245361328]},{"time":0.4,"value":[0.4321664571762085,-0.06509952247142792,-98.42276763916016]},{"time":0.4666666666666667,"value":[0.4321664571762085,-0.0650995522737503,-98.03730773925781]},{"time":0.5,"value":[0.4321664571762085,-0.0650995522737503,-97.9728775024414]},{"time":0.5333333333333333,"value":[0.4321664571762085,-0.06509954482316971,-98.08642578125]},{"time":0.5666666666666667,"value":[0.4321664571762085,-0.06509952992200851,-98.24773406982422]},{"time":0.6,"value":[0.4321664571762085,-0.06509952247142792,-98.41169738769531]},{"time":0.6333333333333333,"value":[0.4321664571762085,-0.06509950757026672,-98.61212921142578]},{"time":0.6666666666666666,"valu
